### ISSUE TITLE
HSBNE Endpoint

### ISSUE THREAD

**Issue by nog3** [slopjong/OpenSpaceDirectory#15]
Hi guys,

Unfortunately our endpoint dropped out at some point and got delisted from SpaceAPI.

I've tried to readd it but it states it's already in the system. Can you please reactivate it? The endpoint address should be http://api.hsbne.org/json

**Comment by slopjong** [comment]
I see your endpoint in the directory. Can you confirm this?

**Comment by nog3** [comment]
Huh, yeah it's showing again. Thanks either way!

**Comment by slopjong** [comment]
@nog3 I didn't do anything to fix it.

The directory you see is regenerated once a day. The magic behind the scene is a revalidator that checks all endpoints to be valid and those that aren't that day are not publicly exposed. This helps to make directory consumers (smartphone apps, webapps, ...) to be more stable.

Reasons for unlisted endpoints can be
- connectivity issues (DNS problem/change, server reboot, ...) which makes them (temporarily) unaccessible during the revalidation process.
- misconfigured web servers that output notices/warnings/errors and making the JSON invalid
- somebody upgrading packages on the endpoint server without checking whether the new ruby/php/python (dist/libs) still work with the endpoint.

That's just an outline and I've seen all of these kind of issues already. The issue could also be on the SpaceAPI side, however, the code hasn't changed for a year. If you encounter the problem again, reopen this issue and let's hunt the bug.
