### ISSUE TITLE
Invalid endpoint for OSAA.

### ISSUE THREAD

**Issue by Skeen** [slopjong/OpenSpaceDirectory#20]
The end point for Open Space Aarhus is pointing to;
http://spaceapi.net/cache/Open+Space+Aarhus
While it should be pointing to;
http://spaceapi.osaa.dk/status/json

I tried to reach out om IRC, but got no response.

**Comment by slopjong** [comment]
I'm currently at work, I'll fix it at noon.

The reason for the wrong URL is that you initially created your endpoint on the spaceapi server but moved it to your own server. I'll change the URL later.

**Comment by slopjong** [comment]
Your URL http://spaceapi.osaa.dk/status/json has already been used internally. You're using the cache which is the reason why the URL doesn't look right for you.
