### ISSUE TITLE
Change Bhack Space API endpoint

### ISSUE THREAD

**Issue by mlowijs** [slopjong/OpenSpaceDirectory#23]
Hello,

Could the Space API endpoint for Bhack be changed to http://api.bhack.nl/SpaceApi

Thanks in advance.

Michiel Lowijs

**Comment by mlowijs** [comment]
Bumping

**Comment by tasomaniac** [comment]
This issue is waiting for a long time. What is the best way to change the endpoint?

**Comment by slopjong** [comment]
Done. Until now the best way is to bump an issue one month later again instead of 7 ;-)

The server will move and more people will be able to work on the project so in the future this shouldn't happen anymore.

**Comment by tasomaniac** [comment]
Thank you. Can you also look at #28
