### ISSUE TITLE
Remove cache feature

### ISSUE THREAD

**Issue by tasomaniac** [slopjong/OpenSpaceDirectory#29]
There was an error in the cached version of the endpoint of Garaj hackerspace: http://spaceapi.net/cache/Garaj

How do I disable using SpaceAPI cache? I don't want to use it? Can we direct the url of our hackerspace to the actual URL:
http://api.garaj.co/spaceapi

Thank you.

**Comment by slopjong** [comment]
Your non-cached version is available now. The endpoint URL might get replaced by the cached one if your endpoint is not accessible during the revalidation. It takes one day to get it your original URL back, automatically.
