### ISSUE TITLE
Directory is empty

### ISSUE THREAD

**Issue by Profpatsch** [slopjong/OpenSpaceDirectory#31]
The directory is empty, apart from the Melbourne Hackerspace.

http://spaceapi.net/directory.json?api=0.13

When I try to add our hackerspace again, I get “Space is already in the directory”.

**Comment by pRiVi** [comment]
Tja, das passiert wenn man auch die kleinsten Tasks gleich mit API und CLOUD machen muss, statt es einfach so zu machen

**Comment by slopjong** [comment]
The directory is fixed. I'm sorry. The disk was full.
