### ISSUE TITLE
SpaceAPI URL changed for coredump

### ISSUE THREAD

**Issue by dbrgn** [slopjong/OpenSpaceDirectory#35]
Old URL: https://status.coredump.ch/

New URL: https://status.crdmp.ch/

**Comment by dbrgn** [comment]
Already covered in a PR: https://github.com/SpaceApi/OpenSpaceDirectory/pull/36

**Comment by dns2utf8** [comment]
See PR: https://github.com/SpaceApi/OpenSpaceDirectory/pull/36
