### ISSUE TITLE
some parts of the API server seem to be down at the moment...

### ISSUE THREAD

**Issue by trailblazr** [slopjong/OpenSpaceDirectory#46]
...or at least do only deliver an empty json which is looking like so 

`{}`

...just recognized this happening today, when my API client tried to fetch the list of hackerspaces.

I think **should definitely cache this list/json** in my future implementations of the client. :-)

**Comment by slopjong** [comment]
Thx for the mail. The directory is back.

**Comment by trailblazr** [comment]
👍🏻  thx. I added caching to the client while the directory was in this status. so future outages would not hit the client a any negative way.
