### ISSUE TITLE
Endpoint change for coredump.ch

### ISSUE THREAD

**Issue by rohieb** [slopjong/OpenSpaceDirectory#7]
From IRC:

```
<dbrgn> [2013-10-24 11:09] hi, could someone change the endpoint URL for "coredump" to http://coredump.ch/status.py?
```

**Comment by slopjong** [comment]
I'll do it tonight. I've no access to the server right now. Can you tell dbrgn that he should remind me in the evening?

**Comment by slopjong** [comment]
Or maybe he's getting a notice if I mention him here. @dbrgn

**Comment by dbrgn** [comment]
Yep, that's me :) What time zone are you in, CET? In that case evening is now :)

**Comment by dbrgn** [comment]
PS: From IRC:

```
14:28 < slopjong> is it correct that your state value is null?
14:28 < slopjong> (i'm talking about your spaceapi endpoint)
14:28 < slopjong> this means that you don't have a sensor connected to it yet
14:33 < slopjong> or are you possibly using the endpoint scripts? https://github.com/SpaceApi/endpoint-scripts
14:33 < slopjong> if so the endpoint status page is not available
```

Yes that is correct. We do not have sensors (yet).

**Comment by slopjong** [comment]
Endpoint URL changed.

**Comment by dbrgn** [comment]
Thanks!

**Comment by dbrgn** [comment]
There is one last change: With our new server infrastructure the endpoint moved to http://status.coredump.ch/. It should now not change anymore.

If you can't access the domain, it's probably a DNS propagation issue and should work inside 12 hours.

**Comment by slopjong** [comment]
Updated. In this case you could have reopened the issue ;-)

**Comment by dbrgn** [comment]
I can't, due to permission issues, as I'm not the author of the first post :)

**Comment by slopjong** [comment]
Hm, I didn't know that only the repo owners and first authors are capable of reopening a ticket. That's quite stupid.

**Comment by dbrgn** [comment]
I think it makes sense to reduce open/close wars, but it should be configurable.

**Comment by slopjong** [comment]
I assume that most github repos are small unknown ones with low traffic. But I agree, popular repos sure would have a problem with reopened issues that should stay closed.
