### ISSUE TITLE
Directory very short

### ISSUE THREAD

**Issue by brimstone** [slopjong/OpenSpaceDirectory#8]
There's only 10 spaces in the directory currently. 

http://spaceapi.net/directory.json

{
   "bytewerk" : "http://spaceapi.net/cache/bytewerk",
   "NURDSpace" : "http://spaceapi.net/cache/NURDSpace",
   "Chaos inKL." : "http://spaceapi.net/cache/Chaos+inKL.",
   "TkkrLab" : "http://spaceapi.net/cache/TkkrLab",
   "Hacksaar" : "http://spaceapi.net/cache/Hacksaar",
   "Nova Labs" : "http://spaceapi.net/cache/Nova+Labs",
   "CCCFr" : "http://spaceapi.net/cache/CCCFr",
   "Frack" : "http://spaceapi.net/cache/Frack",
   "RaumZeitLabor" : "http://spaceapi.net/cache/RaumZeitLabor",
   "H.A.C.K." : "http://spaceapi.net/cache/H.A.C.K.",
   "DevLoL" : "http://spaceapi.net/cache/DevLoL",
   "shackspace - stuttgart hackerspace" : "http://shackspace.de/spaceapi-query-0.13",
   "Tink3rLab" : "http://spaceapi.net/cache/Tink3rLab",
   "coredump" : "http://spaceapi.net/cache/coredump"
}

Where are the rest?

**Comment by slopjong** [comment]
_panic_. I'll look after it in 1 hour.

It wasn't me.

**Comment by slopjong** [comment]
Still @ work. I'm not able to fix it next 10 hours.

**Comment by brimstone** [comment]
On 10/24/2013 03:21 PM, Romain Schmitz wrote:

> Still @ work. I'm not able to fix it next 10 hours.
> What can any of us do to help?

#matt

**Comment by slopjong** [comment]
The problem has gone but I didn't do anything.

**Comment by brimstone** [comment]
If you didn't fix the problem, then the problem isn't fixed.

**Comment by slopjong** [comment]
Things sometimes happen. I'll investigate more intensively if it happens again. If you have some spare time, can you write a little monitoring script to observe the directory length which sends us an email? The treshold should be something like 70-80 entries.
