### ISSUE TITLE
H.A.C.K. implemented SpaceAPI directly

### ISSUE THREAD

**Issue by dnet** [slopjong/OpenSpaceDirectory#9]
We've implemented SpaceAPI directly as of hsbp/hacksense-webmachine@fab13b0 (I don't know where the cached version in the directory came from) the "new" URL is http://vsza.hu/hacksense/spaceapi_status.json

**Comment by slopjong** [comment]
Some time ago I created a [proxy](https://github.com/SpaceApi/OpenSpaceLint/tree/master/c/spacehandlers) for you :-)

Updated now.

@brimstone and @eastein will be able to maintain the directory too in the future but hey're waiting for me to get the howto and other things fixed. @ both: I won't be able to do it next two days. Ping me on Sunday at 10 a.m. UTC+1 or later that day.
